name = "infinity-hackathon-2026"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "infinity-hackathon-bucket"
